
-- -----------------------------------------------------------------------------
-- FISCAL INTELLIGENCE SCHEMA
-- -----------------------------------------------------------------------------
-- Purpose: 
-- Structure for the "Advisor" engine.
-- Stores rules (conditions) and generated alerts/insights.
-- Supports versioning and accountant-only visibility.

-- 1. FISCAL RULES (Knowledge Base)
-- Defines the conditions the engine checks.
-- Can be global (system) or specific overrides.
CREATE TABLE IF NOT EXISTS fiscal_rules (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(50) UNIQUE NOT NULL, -- e.g. 'MEI_REVENUE_LIMIT_WARNING'
    name VARCHAR(255) NOT NULL,
    description TEXT,
    
    category VARCHAR(50) NOT NULL CHECK (category IN ('REVENUE', 'TAX', 'COMPLIANCE', 'RISK')),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    
    condition_json JSONB NOT NULL, -- Logical definition (e.g. { "metric": "YTD_REVENUE", "operator": ">", "threshold_percent": 80 })
    
    recommendation_pt_br TEXT, -- Actionable advice
    
    target_profile VARCHAR(50), -- e.g. 'MEI', 'ME', 'ALL'
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed Basic MEI Rules
INSERT INTO fiscal_rules (code, name, category, severity, condition_json, recommendation_pt_br, target_profile)
VALUES 
('MEI_LIMIT_80', 'Alerta de Limite MEI (80%)', 'REVENUE', 'WARNING', '{"metric": "YTD_REVENUE_PCT", "operator": ">=", "value": 80}', 'Você atingiu 80% do limite anual do MEI. Considere planejar seu desenquadramento com um contador.', 'MEI'),
('TAX_SPIKE_20', 'Aumento Súbito de Impostos', 'TAX', 'INFO', '{"metric": "MONTHLY_TAX_MOM", "operator": ">=", "value": 20}', 'Seus impostos estimados subiram 20% em relação ao mês anterior. Verifique se houve emissão atípica.', 'ALL')
ON CONFLICT (code) DO NOTHING;


-- 2. FISCAL ALERTS (Active Notification State)
-- Generated by the engine when a rule match is found.
CREATE TABLE IF NOT EXISTS fiscal_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL,
    rule_code VARCHAR(50) NOT NULL, -- Link to rule
    
    severity VARCHAR(20) NOT NULL, -- Snapshot from rule
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    
    context_data JSONB, -- Valid values that triggered the alert (e.g. { "current_revenue": 75000, "limit": 81000 })
    
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'READ', 'DISMISSED', 'RESOLVED')),
    
    visibility VARCHAR(20) DEFAULT 'CLIENT' CHECK (visibility IN ('CLIENT', 'ACCOUNTANT_ONLY', 'BOTH')),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP, -- Optional auto-expiration
    
    CONSTRAINT fk_alert_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_alert_rule FOREIGN KEY (rule_code) REFERENCES fiscal_rules(code)
);

CREATE INDEX IF NOT EXISTS idx_fiscal_alerts_company ON fiscal_alerts(company_id, status);


-- 3. FISCAL INSIGHTS (Predictive / Trends)
-- Data points calculated for "Future" visualization (Forecasts).
CREATE TABLE IF NOT EXISTS fiscal_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL,
    type VARCHAR(50) NOT NULL, -- e.g. 'TAX_FORECAST_NEXT_MONTH', 'REVENUE_SEASONALITY'
    
    value_numeric DECIMAL(18, 2),
    value_json JSONB, -- Complex forecast data
    
    confidence_score INTEGER, -- 0-100
    
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valid_until TIMESTAMP,
    
    CONSTRAINT fk_insight_company FOREIGN KEY (company_id) REFERENCES companies(id)
);
